#cloud-config

coreos:
    etcd2:
        name: ${name}
        ca-file: /home/core/ca.crt
        cert-file: /home/core/node.crt
        key-file: /home/core/node.key
        discovery: ${discovery}
        advertise-client-urls: http://$public_ipv4:2379
        initial-advertise-peer-urls: http://$public_ipv4:2380
        listen-client-urls: http://0.0.0.0:2379
        listen-peer-urls: http://$public_ipv4:2380
        election_timeout: 5000
        heartbeat_interval: 1000
    fleet:
        public-ip: $public_ipv4
        etcd-servers: "https://$public_ipv4:2379"
        etcd-cafile: /home/core/ca.crt
        etcd-certfile: /home/core/node.crt
        etcd-keyfile: /home/core/node.key
        metadata: region=${region},host=${name}
    units:
        - name: etcd2.service
          command: start
        - name: fleet.service
          command: start
write_files:
    - path: /etc/profile.d/fleetctl.sh
      permissions: 0644
      owner: core
      content: |
        export FLEETCTL_ENDPOINT="https://$public_ipv4:2379"
        export FLEETCTL_CA_FILE=/home/core/ca.crt
        export FLEETCTL_CERT_FILE=/home/core/node.crt
        export FLEETCTL_KEY_FILE=/home/core/node.key
    - path: /home/core/ca.crt
      permissions: 0444
      owner: core
      content: |
        ${ca}    - path: /home/core/node.crt
      permissions: 0444
      owner: core
      content: |
        ${crt}    - path: /home/core/node.key
      permissions: 0444
      owner: core
      content: |
        ${key}
