#cloud-config

coreos:
    etcd2:
        name: ${name}
        ca-file: /home/core/certs/ca.crt
        cert-file: /home/core/certs/node.crt
        key-file: /home/core/certs/node.key
        peer-ca-file: /home/core/certs/ca.crt
        peer-cert-file: /home/core/certs/node.crt
        peer-key-file: /home/core/certs/node.key
        discovery: ${discovery}
        advertise-client-urls: https://$public_ipv4:2379
        initial-advertise-peer-urls: https://$public_ipv4:2380
        listen-client-urls: https://0.0.0.0:2379
        listen-peer-urls: https://$public_ipv4:2380
        election_timeout: 50000
        heartbeat_interval: 5000
    fleet:
        public-ip: $public_ipv4
        etcd-servers: "https://$public_ipv4:2379"
        etcd-cafile: /home/core/certs/ca.crt
        etcd-certfile: /home/core/certs/node.crt
        etcd-keyfile: /home/core/certs/node.key
        metadata: region=${region},host=${name}
    units:
        - name: etcd2.service
          command: start
        - name: fleet.service
          command: start
        - name: proxii.service
          command: start
          content: |
            [Unit]
            Description=Proxii
            Wants=etcd2.service
            After=etcd2.service

            [Service]
            ExecStart=/etc/usr/bin/rkt --insecure-skip-verify run \
                      --volume certs,kind=host,source=/home/core/certs \
                      https://github.com/blau-io/proxii/releases/download/v0.0.1/proxii.aci \
                      -- -etcdAddress="https://$public_ipv4:2379" \
                         -etcdCaFile=/certs/ca.crt -etcdCertFile=/certs/node.crt \
                         -etcdKeyFile=/certs/node.key
            Restart=always
            RestartSec=10

            [X-Fleet]
            Global=true
    update:
        reboot-strategy: etcd-lock
write_files:
    - path: /etc/profile.d/fleetctl.sh
      permissions: 0644
      owner: core
      content: |
        export FLEETCTL_ENDPOINT="https://$public_ipv4:2379"
        export FLEETCTL_CA_FILE=/home/core/certs/ca.crt
        export FLEETCTL_CERT_FILE=/home/core/certs/node.crt
        export FLEETCTL_KEY_FILE=/home/core/certs/node.key
    - path: /home/core/certs/ca.crt
      permissions: 0444
      owner: core
      content: |
        ${ca}    - path: /home/core/certs/node.crt
      permissions: 0444
      owner: core
      content: |
        ${crt}    - path: /home/core/certs/node.key
      permissions: 0444
      owner: core
      content: |
        ${key}
