#cloud-config

coreos:
    etcd2:
        name: ${name}
        ca-file: /home/core/certs/ca.crt
        cert-file: /home/core/certs/node.crt
        key-file: /home/core/certs/node.key
        peer-ca-file: /home/core/certs/ca.crt
        peer-cert-file: /home/core/certs/node.crt
        peer-key-file: /home/core/certs/node.key
        discovery: ${discovery}
        advertise-client-urls: https://$public_ipv4:2379
        initial-advertise-peer-urls: https://$public_ipv4:2380
        listen-client-urls: https://0.0.0.0:2379
        listen-peer-urls: https://$public_ipv4:2380
        election_timeout: 50000
        heartbeat_interval: 5000
    fleet:
        public-ip: $public_ipv4
        etcd-servers: "https://$public_ipv4:2379"
        etcd-cafile: /home/core/certs/ca.crt
        etcd-certfile: /home/core/certs/node.crt
        etcd-keyfile: /home/core/certs/node.key
        metadata: region=${region},host=${name}
    units:
        - name: etcd2.service
          command: start
        - name: fleet.service
          command: start
    update:
        reboot-strategy: etcd-lock
write_files:
    - path: /home/core/proxii/proxii.service
      permissions: 0644
      owner: core
      content: |
          [Unit]
          Description=Proxii
          Wants=etcd.service
          After=etcd.service

          [Service]
          ExecStartPre=/usr/bin/mkdir -p /home/core/proxii/certs
          ExecStartPre=/usr/bin/cp /home/core/certs/* /home/core/proxii/certs/
          ExecStart=/etc/usr/bin/rkt -insecure-skip-verify run \
          -volume certs,kind=host,source=/home/core/proxii/certs \
          https://github.com/blau-io/proxii/releases/download/v0.0.1/proxii.aci \
          -- -etcdAddress="https://$public_ipv4:2379" \
            -etcdCaFile=/certs/ca.crt -etcdCertFile=/certs/node.crt \
            -etcdKeyFile=/certs/node.key
          Restart=always

          [X-Fleet]
          Global=true
    - path: /etc/profile.d/fleetctl.sh
      permissions: 0644
      owner: core
      content: |
        export FLEETCTL_ENDPOINT="https://$public_ipv4:2379"
        export FLEETCTL_CA_FILE=/home/core/certs/ca.crt
        export FLEETCTL_CERT_FILE=/home/core/certs/node.crt
        export FLEETCTL_KEY_FILE=/home/core/certs/node.key
    - path: /home/core/certs/ca.crt
      permissions: 0444
      owner: core
      content: |
        ${ca}    - path: /home/core/certs/node.crt
      permissions: 0444
      owner: core
      content: |
        ${crt}    - path: /home/core/certs/node.key
      permissions: 0444
      owner: core
      content: |
        ${key}
