#cloud-config

coreos:
    etcd2:
        name: ${name}
        discovery: ${discovery}
        advertise-client-urls: http://$public_ipv4:2379
        initial-advertise-peer-urls: http://$public_ipv4:2380
        listen-client-urls: http://0.0.0.0:2379
        listen-peer-urls: http://$public_ipv4:2380
        election_timeout: 5000
        heartbeat_interval: 1000
    fleet:
        public-ip: $public_ipv4
        metadata: region=${region},host=${name}
    units:
        - name: etcd.service
          command: start
        - name: fleet.service
          command: start
